### ISSUE TITLE
Put News data under revision controllor

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/website-site-ng#14]
If yes, it will be able to check the **history** of revision, and some link(s) (i.e. "Last modified: Jun 1, 2016") will show on somewhere.

This change will affect on the features in #12 and #13.

**Comment by liushuyu** [comment]
But sometimes this function will cause troubles, for there may be some typos or something 'secret' that added to the news accidentally... So this should be handled seriously

**Comment by Yexiaoxing** [comment]
Why not treat as what WikiPedia do? OPs can delete the revision(s) that break(s) the rule.

**Comment by LionNatsu** [comment]
@liushuyu Thanks. Typos are not the problem, but 'secret', which you said, it is a problem.
@Yexiaoxing Great idea, actually OPs obviously can control anything (this is not a self-locking system for high-security purposes.). What it need is to provide an easier way than controlling database directly which may cause critical issue by little mistake.

I have an idea that, every revisions will be indexed by time stamp (guarantee it be unique),  separate it from content creating time. Let the editor be able to **overwrite** the revision directly, at the same time, normally create a new revision and link them together.

**Comment by liushuyu** [comment]
That would be great and I think the `delete` function might be adjusted to something like `git filter-branch` or something like the edit history can be deleted for ever (Like Wikipedia as @Yexiaoxing mentioned before)

**Comment by LionNatsu** [comment]
True, keep a way to overwrite or to delete a certain revision by timestamp index can do so.

**Comment by LionNatsu** [comment]
So the result comes out:
Put it under the revision controllor and provide a way to edit/delete a certain revision.

**Comment by LionNatsu** [comment]
Well... now I think it's really useless for both administrators and viewers.

Discard this issue.
