### ISSUE TITLE
Authenticate

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/website-site-ng#15]
Yesterday, I got an idea:

> **Create a random number[1] as the ticket**, show to the client on the page who required an authentication. Browser keep in touch with server by an pending ajax, to wait the response. The client may **access server's SSH**, and emit an `ACCEPT` to the authenticate program in certain way. After the authenticate program got the acceptation, accomplish the ajax. Then, browser may use the ticket as an argument to do privileged method(s).
*[1] It need a 'real random number'.*

Not bad, and it's easy to implement. (It's just a little bit complex to use...)

**Comment by liushuyu** [comment]
How do you generate a 'real random number' ?

**Comment by LionNatsu** [comment]
@liushuyu It may let the generator refers to time / timers / counters / even CPU temperature... anything unstable and/or unpredictable.

**Comment by liushuyu** [comment]
>It may let the generator refers to time / timers / counters / even CPU temperature... anything unstable and/or unpredictable.

This can be good. May the time proves everything :-)

**Comment by StephDC** [comment]
Is /dev/random acceptable for this real random number generation purpose?

**Comment by Arthur2e5** [comment]
Yes. However, since our server is running on a VPS, the entropy pool …

**Comment by LionNatsu** [comment]
Maybe refers to the time (delay) for accomplishing a connection via GFW is a nice way. (Well, I've already gotten your idea.)

**Comment by Yexiaoxing** [comment]
What about a GUID?

**Comment by LionNatsu** [comment]
@Yexiaoxing ... No, that's a mess.

**Comment by JoyNeop** [comment]
Don't you know random.org?

On Sun, Feb 14, 2016 at 09:12, Lion Yang <notifications@github.com> wrote:
@Yexiaoxing [https://github.com/Yexiaoxing] ... No, that's a mess.

—
Reply to this email directly or view it on GitHub
[https://github.com/AOSC-Dev/website-site-ng/issues/15#issuecomment-183857919] .[https://github.com/notifications/beacon/ACCkfZaH-xmeVeOROPb7hK2Z3Nad5lkaks5pkDx5gaJpZM4HTNGh.gif]

**Comment by Arthur2e5** [comment]
@LionNatsu What do you mean by saying GUIDs are a mess? The randomness of GUIDs comes from your random source.

**Comment by LionNatsu** [comment]
@Arthur2e5 It's just too long to express. Make use of alphabets and numbers can make it shorter.
@JoyNeop Don't be naive = =... I do not want it to depend on a PUBLIC website API, not even it's using HTTPS protocol.

Come on guys... Do not make it too complex...

**Comment by LionNatsu** [comment]
One random number generated for a *expirable* request dump.
Show it, pending for acceptation from SSH.

**Comment by LionNatsu** [comment]
No dump now.
Request for authenticate, expired by redis.
