### ISSUE TITLE
What Page Title Style Shall We Use?

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/website-site-ng#16]
##### Primary Pages

    TITLE · AOSC
    TITLE - AOSC
    TITLE | AOSC
    TITLE / AOSC
    TITLE

##### Secondary Pages(suppose primary pages using `TITLE · AOSC`)

    TITLE · AOSC News
    TITLE · AOSC
    TITLE · News
    TITLE

**Comment by Yexiaoxing** [comment]
I suggest 
`TITLE - AOSC`
and
`TITLE - News - AOSC`

**Comment by LionNatsu** [comment]
@Yexiaoxing May be too long? Or it doesn't matter?

**Comment by MingcongBai** [comment]
Updated the title to make it less confusing.

A `/` looks kinda fun, BTW.

**Comment by Yexiaoxing** [comment]
@LionNatsu it doesn't matter.

**Comment by LionNatsu** [comment]
@Yexiaoxing Got it.
@MingcongBai  Do you mean.... GNU / News (laugh 

(it's a joke

));

**Comment by LionNatsu** [comment]
Well, I decided use the style @Yexiaoxing suggested.

Anyone has better idea can send us here.
