### ISSUE TITLE
No node_modules shall be uploaded to the Git Repo

### ISSUE THREAD

**Issue by Yexiaoxing** [AOSC-Dev/website-site-ng#17]
As what I have said in the telegram group. Instead, a package.json shall be here.

**Comment by LionNatsu** [comment]
package.json is always here.
I am to prune it now.

**Comment by LionNatsu** [comment]
commit: 137f78e32d519b0c05435063a5f71297dcc4d97d

**Comment by MingcongBai** [comment]
You could actually add `fixes #17` to your commit msg so that it will close the issue on push, and reference the commit in this page.
