### ISSUE TITLE
os-download: transition animation played even when clicking on the same tab

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Dev/website-site-ng#26]
Currently, if I click on the "GNOME" tab on the os-download page, and click it again, the "sliding" transition will still play regardless of whether the tab is already activated.

Slightly irritating...

**Comment by LionNatsu** [comment]
Little songs at the first day.

**Comment by MingcongBai** [comment]
> Little songs at the first day.

Yes?

**Comment by LionNatsu** [comment]
Pending for test.

**Comment by LionNatsu** [comment]
Fixed. Closing.

**Comment by MingcongBai** [comment]
Ah, that's better.
