### ISSUE TITLE
site: personal pages for developers/contributors

### ISSUE THREAD

**Issue by MingcongBai** [AOSC-Dev/website-site-ng#37]
Some schools/institutes uses a format like...

```
site.site/~name
```

For hosting personal pages of the faculties or members of an institute. Just an idea, how about we create a system similar to which used with the project sub-pages to provide pages like...

```
https://aosc.io/~icenowy
```

As personal pages for our developers and contributors (any one with valid contribution should be considered eligible).

In addition to all that, we might just use the template for project pages with a header, summary, description, and the actual page contents.

@LionNatsu believes that this should not be done before the data/contents are split from the website repository.

**Comment by liushuyu** [comment]
@MingcongBai I believe it's good to mark this as resolved?

**Comment by MingcongBai** [comment]
@liushuyu Yep.

**Comment by liushuyu** [comment]
For the record, the initial solution is in 9de1f5e8d5986499eacea1248ebbcd28d3bc90fc
