### ISSUE TITLE
test: add test for RSS/Sitemap

### ISSUE THREAD

**Issue by LionNatsu** [AOSC-Dev/website-site-ng#49]
cc: @liushuyu @LER0ever @MingcongBai

**Comment by MingcongBai** [comment]
Unit test?

**Comment by LionNatsu** [comment]
Yes, I mean Mocha.

**Comment by MingcongBai** [comment]
I see. @liushuyu we will need your help.

**Comment by liushuyu** [comment]
So how to make this test? Just test if the XML structure is valid.

**Comment by LionNatsu** [comment]
@liushuyu 
Yes, to test if it (/sitemap... ) can be run if it's output is a valid structure. Any other thoughts?

**Comment by liushuyu** [comment]
More sophisticated test can include like if RSS feed include all the entries in new-db. But that's hard to implement imo

**Comment by liushuyu** [comment]
Oh, forgot to close this one... Actually the tests are done, however it seems like the package `feed` does not want to comply with the standard `feed` format.
