### ISSUE TITLE
People page apparently lacks grid placement

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Dev/website-site-ng#61]

**Comment by MingcongBai** [comment]
It seems like the rows were not regarded properly. Because as in the code each "person" gets a 6 columns wide grid.

**Comment by MingcongBai** [comment]
Maybe @LionNatsu knows what to do here...

**Comment by LionNatsu** [comment]
Fixed at 42d47e298878f32f254b940036e033639221978b
