### ISSUE TITLE
Remove tilde (~) for "people" pages if they are always put under a fixed path (/people/)

### ISSUE THREAD

**Issue by Artoria2e5** [AOSC-Dev/website-site-ng#62]

**Comment by MingcongBai** [comment]
Closing. Voted by design.

**Comment by gumblex** [comment]
Make a 301?

**Comment by Artoria2e5** [comment]
The awkward point about `people/~` is that `^~` tends to be something that's concealed (e.g. not indexed by many indexing modules), and you are effectively akarin-izing a whole directory. Makes no sense, I mean.

**Comment by Artoria2e5** [comment]
(A worse part in the current people system is that it gives not a directory, but a single pig-framed webpage for users to use. Where is the "home" implied by the tilde?)
